// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irgucntqbhswunlchbot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ3VjbnRxYmhzd3VubGNoYm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjA4NDAsImV4cCI6MjA2NDQ5Njg0MH0.ZzUR7u71UTylvcv64_Wt2hj7pLxNMgPBZIXNyUfNpo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);